### ISSUE TITLE
Issues with cursor positions after Atom 1.1

### ISSUE THREAD

**Issue by milose** [Kelvinrr/seafoam-syntax#1]
Hello,

I have issue with this theme after updating to Atom 1.1 and Atom 1.2

This is some random theme, and you can see the cursor has a correct position when you type or click.
![screen capture on 2015-11-16 at 14-11-09](https://cloud.githubusercontent.com/assets/2998029/11182633/74d19e22-8c6c-11e5-81c0-01bfc26fc802.gif)

With seafom you can see the offset with the cursor when you type, but not when you select.
![screen capture on 2015-11-16 at 14-12-54](https://cloud.githubusercontent.com/assets/2998029/11182637/779436c4-8c6c-11e5-9ec9-86640cc7a150.gif)

What do you reckon might be the issue?

Kind regards,
Milos

**Comment by Kelvinrr** [comment]
Hi, thanks for pointing it out. It was a simple padding issue. Fixed in the last update.
